language: cpp

matrix:
  include:
    # windows msvc
    - name: "Windows / MSVC"
      os: windows
      script:
        - cmd.exe /C 'build_and_test_msvc.bat release "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"'

    # windows clang
    - name: "Win64 / Clang"
      os: windows
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
        - COMPILER=clang
      before_script:
        - chmod +x build_linux_clang_gcc.sh
        - chmod +x build_and_test.sh
      script: ./build_and_test.sh ${COMPILER} release

    # windows gcc
    - name: "Win64 / GCC"
      os: windows
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - COMPILER=gcc
      before_script:
        - chmod +x build_linux_clang_gcc.sh
        - chmod +x build_and_test.sh
      script: ./build_and_test.sh ${COMPILER} release

    # linux clang
    - name: "Linux / Clang"
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      before_install:
        - CC=clang-7
        - CXX=clang++-7
        - COMPILER=clang
      install:
        - ${CC} --version
      before_script:
        - chmod +x build_linux_clang_gcc.sh
        - chmod +x build_and_test.sh
      script: ./build_and_test.sh ${COMPILER} release

    # linux gcc
    - name: "Linux / GCC"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      before_install:
        - CC=gcc-8
        - CXX=g++-8
        - COMPILER=gcc
      install:
        - ${CC} --version
      before_script:
        - chmod +x build_linux_clang_gcc.sh
        - chmod +x build_and_test.sh
      script: ./build_and_test.sh ${COMPILER} release

    # macOS
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
      compiler: clang
      before_script:
        - chmod +x build_linux_clang_gcc.sh
        - chmod +x build_and_test.sh
      script: ./build_and_test.sh ${CXX} release
