name: CI

on:
  push:
    branches: [ v2.0.0 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: ["clang", "gcc", "msvc"]

    steps:
      - uses: actions/checkout@v2

      - name: Install Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build And Test
        run: .\scripts\build_and_test_clang.bat ${{ matrix.compiler }}