name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ v2.0.0 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  #
  # build generator
  #
  build-generator:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Generator
        run: .\scripts\build_generator.bat --config debug

  tests-clang:
    runs-on: windows-latest
    needs: build-generator
    name: Clang
    steps:
      - run: .\scripts\build_and_test_clang.bat